### ISSUE TITLE
Incompatibility Issues with Firebase/Messaging and FBAudienceNetwork after Updating to Appodeal-Flutter-Plugin 3.3.0

### ISSUE THREAD

**Issue by mohamedalwhaidi** [appodeal/Appodeal-Flutter-Plugin#74]
### Description
After updating the Appodeal-Flutter-Plugin to version 3.3.0, I encountered dependency incompatibility issues with Firebase/Messaging and FBAudienceNetwork when running `pod update`.

### Steps to Reproduce
1. Update Appodeal-Flutter-Plugin to version 3.3.0 in `pubspec.yaml`.
2. Run `pod update` in the iOS project directory.
3. Observe the dependency conflict errors.

### Expected Behavior
The `pod update` command should update all dependencies without any version conflicts.

### Actual Behavior
Running `pod install` results in the following errors:

#### Error 1:
firebase_remote_config: Using Firebase SDK version '10.25.0' defined in 'firebase_core'
[!] CDN: trunk URL couldn't be downloaded: https://cdn.cocoapods.org/Specs/2/d/6/FirebaseMessaging/10.25.0/FirebaseMessaging.podspec.json Response: Failure when receiving data from the peer

Running `pod update` results in the following errors:

#### Error 2:
[!] CocoaPods could not find compatible versions for pod "Firebase/Messaging":
In snapshot (Podfile.lock):
Firebase/Messaging (= 10.15.0)

In Podfile:
firebase_messaging (from .symlinks/plugins/firebase_messaging/ios) was resolved to 14.9.2, which depends on
Firebase/Messaging (= 10.25.0)

You have either:

changed the constraints of dependency Firebase/Messaging inside your development pod firebase_messaging.
You should run pod update Firebase/Messaging to apply changes you've made.

Running `pod update Firebase/Messaging` results in another error:

#### Error 3:

[!] CocoaPods could not find compatible versions for pod "Firebase/InAppMessaging":
  In snapshot (Podfile.lock):
    Firebase/InAppMessaging (= 10.15.0)

  In Podfile:
    firebase_in_app_messaging (from `.symlinks/plugins/firebase_in_app_messaging/ios`) was resolved to 0.7.5-5, which depends on
      Firebase/InAppMessaging (= 10.25.0)

You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * changed the constraints of dependency `Firebase/InAppMessaging` inside your development pod `firebase_in_app_messaging`.
   You should run `pod update Firebase/InAppMessaging` to apply changes you've made.

### Flutter Doctor Output
[✓] Flutter (Channel stable, 3.19.5, on macOS 14.4.1 23E224 darwin-arm64, locale en-PS)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.2)
[✓] VS Code (version 1.89.1)
[✓] Connected device (3 available)
    ! Error: Browsing on the local area network for The Once Mohamed  🔥. Ensure the device is unlocked and attached with a cable or associated with
      the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code -27)
[✓] Network resources

### Additional Context
These issues started occurring after upgrading to Appodeal-Flutter-Plugin 3.3.0. The project builds successfully before the update. Please advise on how to resolve these dependency conflicts.

**Comment by da2gl** [comment]
@mohamedalwhaidi Hi,
**Error 1: CDN problem**
The error you're encountering indicates a problem with accessing the CDN (Content Delivery Network) for CocoaPods, specifically when trying to download a podspec file for FirebaseMessaging version 10.25.0. Here are some steps you can take to resolve this issue:

- Check Internet Connection:
Ensure your internet connection is stable and that there are no network issues. Sometimes, this error can occur due to temporary connectivity problems.

- Update CocoaPods:
Ensure you have the latest version of CocoaPods installed:
```bash
sudo gem install cocoapods
```
- Clear CocoaPods Cache:
Sometimes cached data might be corrupt or outdated. Clear the CocoaPods cache by running:
```bash
pod cache clean --all
```
- Update Pod Repo:
Update the CocoaPods repository to make sure you have the latest specs:
```bash
pod repo update
```
- Use an Alternate Source:
If the main CDN is down or having issues, you can try switching to an alternate source like:

```ruby
source 'https://github.com/CocoaPods/Specs.git'
source 'https://cdn.cocoapods.org/'
```
Add these lines to the top of your Podfile.

- Check Firewall/Proxy Settings:
If you're behind a firewall or using a proxy, ensure that it is not blocking the request to the CocoaPods CDN.


**Error 2 and Error 3: Version Conflicts**
These errors arise from conflicting versions between your Podfile and the locked versions in Podfile.lock.

- Open Podfile.lock and remove the lines related to Firebase/Messaging and Firebase/InAppMessaging. This forces CocoaPods to resolve versions anew.
- Run pod update Firebase/Messaging Firebase/InAppMessaging after modifying the Podfile.lock.

**Final Steps**
- Ensure All Dependencies Are Up-to-Date:
```bash
pod update
```
- Run Pod Install:
```bash
pod install --repo-update
```
